export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { Toaster } from "../components/ui/toaster";
import "./globals.css"; // 导入全局样式文件
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
